### ISSUE TITLE
[1.12] Solcarrot crash: onFoodEaten(SOLCarrotModule.java:81)

### ISSUE THREAD

**Issue by Krutoy242** [yeelp/Scaling-Feast#125]
**Mod Version**: v1.8.2
**Minecraft Version**: 1.12.2
**Loaded Mods**: [E2E-E modpack](https://github.com/Krutoy242/Enigmatica2Expert-Extended) (Not tested on small list)

**Describe the bug**
Various game events causing this crash:
```less
java.util.concurrent.ExecutionException: java.util.NoSuchElementException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
[...]
Caused by: java.util.NoSuchElementException
    at java.util.LinkedList.removeLast(LinkedList.java:283)
    at yeelp.scalingfeast.integration.module.solcarrot.SOLCarrotModule$1.onFoodEaten(SOLCarrotModule.java:81)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_4665__onFoodEaten_FoodEaten.invoke(.dynamic)
```

**Steps to Reproduce**
Not stably reproducible.
Sometimes it happen when mining the ore: Exhausted Netherrack.
Sometimes - when hunger bar changed by eating.

**Screenshots**
![](https://i.imgur.com/48aw7av.png)

**Additional context**
[crash-2022-03-21_20.22.45-client.txt](https://github.com/yeelp/Scaling-Feast/files/8322344/crash-2022-03-21_20.22.45-client.txt)
[crash-2022-03-21_21.15.57-client.txt](https://github.com/yeelp/Scaling-Feast/files/8322345/crash-2022-03-21_21.15.57-client.txt)

**Comment by Aeron216** [comment]
Ive been getting similar crashes. Not easily reproducible either:

From a friend:
https://pastes.dev/szQiVqqMOX

One that happened to me, happened as soon as I consumed an Emerald Apple from Pickle Tweaks.
https://gist.github.com/Aeron216/10c248b2974143f3f9dec76b0feeaba9

**Comment by yeelp** [comment]
This is very strange. I've seen this happen to many others but I'm unable to reproduce this myself. I'll add a check that avoids this situation. Not the best fix, but it should work.
