### ISSUE TITLE
Crash with Dank Null

### ISSUE THREAD

**Issue by MysteriousDownloader** [yeelp/Scaling-Feast#86]
**1.5.1*: (Replace this with the Mod's version that you are using.)
**1.12.2**: (Replace this with the version of Minecraft you are using.)
**2**: (Replace this with the smallest possible list of mods you can load alongside Scaling Feast to reproduce this bug. This should typically only be one or two mods. Do not include AppleCore, library mods, or other core mods unless the problem lies specifically with these mods.) 

**Describe the bug**
Opening dank null with Display Style: OVERLAY crash

**Steps to Reproduce**
1.Set Display Style to OVERLAY 
2.Open DankNull

**Expected behavior**
Instant Game Crash

**Screenshots**
(Replace this if applicable, with screenshots to help explain your problem. Otherwise, remove this section.)

**Additional context**
---- Minecraft Crash Report ----

WARNING: coremods are present:
  AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 7/1/20 9:42 PM
Description: Unexpected error

java.lang.UnsupportedOperationException: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.client.event.RenderGameOverlayEvent.Post
	at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:96)
	at p455w0rd.danknull.init.ModEvents.renderOverlayEvent(ModEvents.java:96)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_22_ModEvents_renderOverlayEvent_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at yeelp.scalingfeast.handlers.HUDOverlayHandler.onPreRender(HUDOverlayHandler.java:183)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_46_HUDOverlayHandler_onPreRender_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.renderFood(GuiIngameForge.java:493)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:156)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:96)
	at p455w0rd.danknull.init.ModEvents.renderOverlayEvent(ModEvents.java:96)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_22_ModEvents_renderOverlayEvent_RenderGameOverlayEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at yeelp.scalingfeast.handlers.HUDOverlayHandler.onPreRender(HUDOverlayHandler.java:183)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_46_HUDOverlayHandler_onPreRender_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.renderFood(GuiIngameForge.java:493)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:156)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DarkNote32'/28, l='MpServer', x=2339.45, y=4.00, z=-241.62]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (2337,4,-241), Chunk: (at 1,0,15 in 146,-16; contains blocks 2336,0,-256 to 2351,255,-241), Region: (4,-1; contains chunks 128,-32 to 159,-1, blocks 2048,0,-512 to 2559,255,-1)
	Level time: 417 game time, 417 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 40 total; [EntityCow['Cow'/70977, l='MpServer', x=2347.50, y=4.00, z=-205.50], EntityPlayerSP['DarkNote32'/28, l='MpServer', x=2339.45, y=4.00, z=-241.62], EntityHorse['Horse'/70976, l='MpServer', x=2292.50, y=4.00, z=-260.50], EntityHorse['Horse'/70981, l='MpServer', x=2351.50, y=4.00, z=-206.50], EntityHorse['Horse'/70983, l='MpServer', x=2352.50, y=4.00, z=-208.50], EntityChicken['Chicken'/70985, l='MpServer', x=2266.50, y=4.00, z=-311.50], EntityCow['Cow'/70984, l='MpServer', x=2344.50, y=4.00, z=-203.50], EntityChicken['Chicken'/70987, l='MpServer', x=2275.50, y=4.00, z=-309.50], EntityChicken['Chicken'/70986, l='MpServer', x=2271.50, y=4.00, z=-306.50], EntityChicken['Chicken'/70988, l='MpServer', x=2280.56, y=4.00, z=-306.52], EntitySlime['Slime'/70553, l='MpServer', x=2353.31, y=4.00, z=-312.88], EntityCow['Cow'/71005, l='MpServer', x=2333.50, y=4.00, z=-207.50], EntityCow['Cow'/71004, l='MpServer', x=2332.50, y=4.00, z=-210.50], EntitySheep['Sheep'/71007, l='MpServer', x=2339.50, y=4.00, z=-206.50], EntitySheep['Sheep'/71006, l='MpServer', x=2339.50, y=4.00, z=-208.50], EntitySlime['Slime'/70753, l='MpServer', x=2375.78, y=4.00, z=-179.30], EntityChicken['Chicken'/71013, l='MpServer', x=2393.50, y=4.00, z=-172.50], EntitySlime['Slime'/60901, l='MpServer', x=2371.92, y=4.14, z=-294.96], EntitySheep['Sheep'/71012, l='MpServer', x=2387.50, y=4.00, z=-168.50], EntityChicken['Chicken'/71014, l='MpServer', x=2391.50, y=4.00, z=-169.50], EntityHorse['Horse'/71017, l='MpServer', x=2390.50, y=4.00, z=-171.50], EntityHorse['Horse'/71016, l='MpServer', x=2390.50, y=4.00, z=-169.50], EntityPig['Pig'/71023, l='MpServer', x=2410.50, y=4.00, z=-249.50], EntityPig['Pig'/71025, l='MpServer', x=2417.50, y=4.00, z=-249.50], EntityPig['Pig'/71024, l='MpServer', x=2413.50, y=4.00, z=-251.50], EntityChicken['Chicken'/71027, l='MpServer', x=2400.50, y=4.00, z=-229.50], EntityPig['Pig'/71026, l='MpServer', x=2416.50, y=4.00, z=-252.50], EntitySheep['Sheep'/71029, l='MpServer', x=2412.50, y=4.00, z=-234.50], EntitySheep['Sheep'/71028, l='MpServer', x=2407.50, y=4.00, z=-231.50], EntitySheep['Sheep'/71031, l='MpServer', x=2411.50, y=4.00, z=-234.50], EntityCow['Cow'/70969, l='MpServer', x=2300.50, y=4.00, z=-258.50], EntityPig['Pig'/71033, l='MpServer', x=2318.50, y=4.00, z=-167.50], EntitySlime['Slime'/40825, l='MpServer', x=2303.62, y=4.00, z=-236.68], EntityCow['Cow'/70968, l='MpServer', x=2299.50, y=4.00, z=-258.50], EntityPig['Pig'/71032, l='MpServer', x=2322.50, y=4.00, z=-165.50], EntityHorse['Horse'/70971, l='MpServer', x=2295.50, y=4.00, z=-259.50], EntityPig['Pig'/71035, l='MpServer', x=2326.50, y=4.00, z=-171.50], EntityCow['Cow'/70970, l='MpServer', x=2300.50, y=4.00, z=-261.50], EntityPig['Pig'/71034, l='MpServer', x=2324.50, y=4.00, z=-169.50], EntityHorse['Horse'/70975, l='MpServer', x=2292.50, y=4.00, z=-258.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 487353128 bytes (464 MB) / 905969664 bytes (864 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2838 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID           | Version      | Source                          | Signature                                |
	|:------ |:------------ |:------------ |:------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft    | 1.12.2       | minecraft.jar                   | None                                     |
	| LCHIJA | mcp          | 9.42         | minecraft.jar                   | None                                     |
	| LCHIJA | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2838.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge        | 14.23.5.2838 | forge-1.12.2-14.23.5.2838.jar   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | applecore    | 3.4.0        | AppleCore-mc1.12.2-3.4.0.jar    | None                                     |
	| LCHIJA | p455w0rdslib | 2.3.161      | p455w0rdslib-1.12.2-2.3.161.jar | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
	| LCHIJA | danknull     | 1.7.90       | DankNull-1.12.2-1.7.90.jar      | None                                     |
	| LCHIJA | scalingfeast | v1.5.1       | scalingfeast-1.5.1.jar          | None                                     |

	Loaded coremods (and transformers): 
AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 20.3.1 26.20.15029.15007' Renderer: 'Radeon RX 5500 XT'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2838
	LWJGL: 2.9.4
	OpenGL: Radeon RX 5500 XT GL version 4.6.13587 Compatibility Profile Context 20.3.1 26.20.15029.15007, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 2400G with Radeon Vega Graphics

**Comment by yeelp** [comment]
Can I get the version of DankNull you're using? If you're not using the latest, can you check to see if the problem occurs using the latest version of DankNull? The problematic line this crash log references doesn't match up with DankNull's GitHub.

I'm suspecting this is an issue with Dank Null, as it is trying to cancel an event that can't be canceled. You can try disabling the compatibility settings in Scaling Feast, although this may remove some HUD elements from other mods.

I'm going to get in touch with the developer of DankNull about this.

**Comment by MysteriousDownloader** [comment]
I used DankNull 1.7.90 then changed to 1.7.91 still crashed. But then I disabled the compatibility settings in Scaling Feast and it worked

**Comment by cjm721** [comment]
Version 90 and 91 of dank-null are very much out of date. 101 is currently the latest, marked as beta because it will cause a dank-null storage wipe on update from pre-version 95.

**Comment by yeelp** [comment]
There's nothing Scaling Feast can do about this right now, and the problem that causes this crash is fixed on later versions of DankNull, so I'm closing this issue.
